export const INSTAGRAM_API_VERSION = process.env.INSTAGRAM_API_VERSION;

export const INSTAGRAM_GRAPH_BASE_URL = process.env.INSTAGRAM_GRAPH_BASE_URL;

export const INSTAGRAM_OAUTH_BASE_URL = process.env.INSTAGRAM_OAUTH_BASE_URL;

export const INSTAGRAM_AUTHORIZE_BASE_URL =
  process.env.INSTAGRAM_AUTHORIZE_BASE_URL;
